### PR TITLE
Use addEventListener for search engine presets

### PR DESCRIPTION
**Pull request by hello-smile6**
Should fix https://github.com/MystPi/ninetails/pull/65#pullrequestreview-835802865

### CODE REVIEW

**Comment by hello-smile6** [comment]
Not ready to merge yet

**Comment by Darth-Ness** [comment]
Oh oh, I did this too. Does yours have dropdown styling?

**Comment by hello-smile6** [comment]
> Oh oh, I did this too. Does yours have dropdown styling?

Adding dropdown.

**Comment by hello-smile6** [comment]
Ready to merge

**Review by Darth-Ness — CHANGES_REQUESTED** [review]
What about dropdowns? If you would like me to post my code for dropdowns I can. Thanks for helping!

**Comment by hello-smile6** [comment]
Could you use yours?

**Comment by Darth-Ness** [comment]
> Could you use yours?

All right, I did.

**Pull request closed without merging**
